language: c

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="cmake libclutter-gst-3.0-dev libclutter-gtk-1.0-dev libgranite-dev libgtk-3-dev valac"

before_install:
 - docker pull ubuntu:16.04
 - docker run -v "$PWD":/tmp/git-dir ubuntu:16.04 /bin/sh -c "apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:elementary-os/daily && add-apt-repository -y ppa:elementary-os/os-patches && apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/git-dir && cmake . && make"

script:
 - echo BUILD PASSED
